name: dbmigrator
description: A database-agnostic foundation for building structured database migration tools in Dart.
version: 0.1.1
repository: https://github.com/paschalisp/dbmigrator-dart
homepage: https://github.com/paschalisp/dbmigrator-dart
topics:
  - database
  - migration
  - postgresql
  - mysql
  - mssql

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  pub_semver: ^2.2.0
  crypto: ^3.0.7

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
